name: 1024-AutoReply

on:
  workflow_dispatch: # 手动触发
#  push: 取消Push的方式触发工作流，方便多次提交修改代码后统一调试
#    branches:
#      - master
  schedule:
   - cron: '0/10 22,4,10 * * *' #北京时间06:00、12:00、18:00,每十分钟执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 准备脚本运行环境 01
      uses: actions/checkout@v2
    - name: 准备脚本运行环境 02
      run : |
        sudo apt-get update
        sudo apt-get -y install git python3-pip python3-setuptools
        pip3 install requests onetimepass pillow
    - name: 开始1024自动回复
      env:
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SECRET: ${{ secrets.SECRET }}
        TOKER: ${{ secrets.TOKER }}
        CODEUSER: ${{ secrets.CODEUSER }}
        CODEPASS: ${{ secrets.CODEPASS }}
      run:
        python3 1024.py
